services:
  database:
    image: mariadb:10.6.4-focal
    container_name: '${BRAND_NAME}_database'
    restart: unless-stopped
    ports:
      - '3307:3306'
    env_file: .env
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      UPLOAD_LIMIT: 512M
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 300
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network

  phpmyadmin:
    container_name: '${BRAND_NAME}_phpmyadmin'
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network

  wordpress:
    container_name: '${BRAND_NAME}_wordpress'
    depends_on:
      - database
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - wordpress-core:/var/www/html/
      - ./my_theme:/var/www/html/wp-content/themes/my_theme
       - ./Astra:/var/www/html/wp-content/themes/astra

    networks:
      - wordpress-network

volumes:
  db-data:
  wordpress-core:

networks:
  wordpress-network:
    driver: bridge
